version: 2
jobs:
  build:
    docker:
      - image: checkmarx/ast-cli
    steps:
      - checkout
      - run:
          name: "Run Scan"
          command: |
            /app/bin/cx \
            scan create \
            -s '.' \
            --agent 'CircleCI' \
            --project-name 'totallysecureapp circleci' \
            --branch 'master' \
            --base-uri 'https://ast.checkmarx.net/' \
            --base-auth-uri 'https://iam.checkmarx.net/' \
            --tenant 'cx_ast_se_allengay_demo_na' \
            --client-id 'circleci_client' \
            --client-secret 'm440LBJpsqo1IECTDBC823aVOmFiVv2a' \
